services:
  notification.email:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET-KEY=${JWT_SECRET-KEY}
      - JWT_EXPIRATION-TIME=${JWT_EXPIRATION-TIME}
    volumes:
      - ./target/ProjectPulse-0.0.1-SNAPSHOT.jar:/app.jar